Quiz.all.destroy_all
Question.all.destroy_all
Answer.all.destroy_all

puts "🤔 Seeding Quizzes..."
Quiz.create(topic: "Math", title: "Addition")
Quiz.create(topic: "Science", title: "Photosynthesis")
Quiz.create(topic: "History", title: "World War II")
Quiz.create(topic: "Programming", title: "Ruby Methods")

puts "❓ Seeding Questions..."
# Math Questions:
Question.create(question: "What is 1 + 1?", quiz_id: Quiz.all[0].id)
Question.create(question: "What is 3 * 3?", quiz_id: Quiz.all[0].id)
Question.create(question: "What is 9 / 3?", quiz_id: Quiz.all[0].id)
Question.create(question: "What is 11 - 3?", quiz_id: Quiz.all[0].id)
Question.create(question: "What is the square root of 144?", quiz_id: Quiz.all[0].id)
# Science Questions
Question.create(question: "What is a byproduct of photosynthesis?", quiz_id: Quiz.all[1].id)
Question.create(question: "How long does it take the earth to do one full rotation around the sun?", quiz_id: Quiz.all[1].id)
Question.create(question: "Why do our pupils constrict in bright light?", quiz_id: Quiz.all[1].id)
Question.create(question: "What is cooling lava called?", quiz_id: Quiz.all[1].id)
Question.create(question: "What's faster: sound or light?", quiz_id: Quiz.all[1].id)
# WWII Questions
Question.create(question: "On what date did the war end?", quiz_id: Quiz.all[2].id)
Question.create(question: "Which event is generally considered to be the first belligerent act of World War II?", quiz_id: Quiz.all[2].id)
Question.create(question: "Which two countries were the first to declare war on Germany?", quiz_id: Quiz.all[2].id)
Question.create(question: "Against which country did the Soviet Union instigate an armed conflict in late 1939?", quiz_id: Quiz.all[2].id)
Question.create(question: "What were the first two western European countries that Germany invaded?", quiz_id: Quiz.all[2].id)
# Programming Questions
Question.create(question: "Which method adds an element to the end of an array?", quiz_id: Quiz.all[3].id)
Question.create(question: "Which method adds an element to the beginning of an array?", quiz_id: Quiz.all[3].id)
Question.create(question: "Which method permanently removes the last element of an array?", quiz_id: Quiz.all[3].id)
Question.create(question: "Which method permanently removes the first element of an array?", quiz_id: Quiz.all[3].id)
Question.create(question: "Which method copies and clones an array?", quiz_id: Quiz.all[3].id)

puts "❗ Seeding Answers..."
# Math Answers
Answer.create(answer: "2", correct: true, question_id: Question.all[0].id)
Answer.create(answer: "1", correct: false, question_id: Question.all[0].id)
Answer.create(answer: "3", correct: false, question_id: Question.all[0].id)
Answer.create(answer: "19", correct: false, question_id: Question.all[0].id)
Answer.create(answer: "6", correct: false, question_id: Question.all[1].id)
Answer.create(answer: "19", correct: false, question_id: Question.all[1].id)
Answer.create(answer: "9", correct: true, question_id: Question.all[1].id)
Answer.create(answer: "42", correct: false, question_id: Question.all[1].id)
Answer.create(answer: "2", correct: false, question_id: Question.all[2].id)
Answer.create(answer: "4", correct: false, question_id: Question.all[2].id)
Answer.create(answer: "9", correct: false, question_id: Question.all[2].id)
Answer.create(answer: "3", correct: true, question_id: Question.all[2].id)
Answer.create(answer: "17", correct: false, question_id: Question.all[3].id)
Answer.create(answer: "8", correct: true, question_id: Question.all[3].id)
Answer.create(answer: "9", correct: false, question_id: Question.all[3].id)
Answer.create(answer: "16", correct: false, question_id: Question.all[3].id)
Answer.create(answer: "10", correct: false, question_id: Question.all[4].id)
Answer.create(answer: "15", correct: false, question_id: Question.all[4].id)
Answer.create(answer: "1", correct: false, question_id: Question.all[4].id)
Answer.create(answer: "12", correct: true, question_id: Question.all[4].id)
# Science Answers
Answer.create(answer: "Oxygen", correct: true, question_id: Question.all[5].id)
Answer.create(answer: "Carbon Dioxide", correct: false, question_id: Question.all[5].id)
Answer.create(answer: "Water", correct: false, question_id: Question.all[5].id)
Answer.create(answer: "Potatoes", correct: false, question_id: Question.all[5].id)
Answer.create(answer: "366", correct: false, question_id: Question.all[6].id)
Answer.create(answer: "365", correct: true, question_id: Question.all[6].id)
Answer.create(answer: "220", correct: false, question_id: Question.all[6].id)
Answer.create(answer: "1176", correct: false, question_id: Question.all[6].id)
Answer.create(answer: "To make us look nicer", correct: false, question_id: Question.all[7].id)
Answer.create(answer: "To give our eyes more oxygen", correct: false, question_id: Question.all[7].id)
Answer.create(answer: "To change our vision to 3D", correct: false, question_id: Question.all[7].id)
Answer.create(answer: "To let in less light", correct: true, question_id: Question.all[7].id)
Answer.create(answer: "Magma", correct: true, question_id: Question.all[8].id)
Answer.create(answer: "Lava Lite", correct: false, question_id: Question.all[8].id)
Answer.create(answer: "Igneous Lava", correct: false, question_id: Question.all[8].id)
Answer.create(answer: "Fossils", correct: false, question_id: Question.all[8].id)
Answer.create(answer: "Sound", correct: false, question_id: Question.all[9].id)
Answer.create(answer: "Light", correct: true, question_id: Question.all[9].id)
Answer.create(answer: "They travel at the same speed", correct: false, question_id: Question.all[9].id)
Answer.create(answer: "They don't move", correct: false, question_id: Question.all[9].id)
# WWII Answers
Answer.create(answer: "September 2, 1945", correct: true, question_id: Question.all[10].id)
Answer.create(answer: "October 5, 1984", correct: false, question_id: Question.all[10].id)
Answer.create(answer: "September 25, 2010", correct: false, question_id: Question.all[10].id)
Answer.create(answer: "August 16, 2020", correct: false, question_id: Question.all[10].id)
Answer.create(answer: "Germany's attack on Russia", correct: false, question_id: Question.all[11].id)
Answer.create(answer: "Germany's attack on Britain", correct: false, question_id: Question.all[11].id)
Answer.create(answer: "Germany's attack on Poland", correct: true, question_id: Question.all[11].id)
Answer.create(answer: "Germany's occupation of Austria", correct: false, question_id: Question.all[11].id)
Answer.create(answer: "Italy and Greece", correct: false, question_id: Question.all[12].id)
Answer.create(answer: "Britain and France", correct: true, question_id: Question.all[12].id)
Answer.create(answer: "Norway and Denmark", correct: false, question_id: Question.all[12].id)
Answer.create(answer: "The United States and the USSR", correct: false, question_id: Question.all[12].id)
Answer.create(answer: "Finland", correct: true, question_id: Question.all[13].id)
Answer.create(answer: "Yugoslavia", correct: false, question_id: Question.all[13].id)
Answer.create(answer: "Czechoslovakia", correct: false, question_id: Question.all[13].id)
Answer.create(answer: "Hungary", correct: false, question_id: Question.all[13].id)
Answer.create(answer: "France and Belgium", correct: false, question_id: Question.all[14].id)
Answer.create(answer: "Norway and Denmark", correct: true, question_id: Question.all[14].id)
Answer.create(answer: "Switzerland and Liechtenstein", correct: false, question_id: Question.all[14].id)
Answer.create(answer: "Austria and the Netherlands", correct: false, question_id: Question.all[14].id)

# Programming Answers
Answer.create(answer: ".pop", correct: false, question_id: Question.all[15].id)
Answer.create(answer: ".shift", correct: false, question_id: Question.all[15].id)
Answer.create(answer: ".push", correct: true, question_id: Question.all[15].id)
Answer.create(answer: ".unshift", correct: false, question_id: Question.all[15].id)
Answer.create(answer: ".pop", correct: false, question_id: Question.all[16].id)
Answer.create(answer: ".shift", correct: false, question_id: Question.all[16].id)
Answer.create(answer: ".push", correct: false, question_id: Question.all[16].id)
Answer.create(answer: ".unshift", correct: true, question_id: Question.all[16].id)
Answer.create(answer: ".pop", correct: true, question_id: Question.all[17].id)
Answer.create(answer: ".shift", correct: false, question_id: Question.all[17].id)
Answer.create(answer: ".push", correct: false, question_id: Question.all[17].id)
Answer.create(answer: ".unshift", correct: false, question_id: Question.all[17].id)
Answer.create(answer: ".pop", correct: false, question_id: Question.all[18].id)
Answer.create(answer: ".shift", correct: true, question_id: Question.all[18].id)
Answer.create(answer: ".push", correct: false, question_id: Question.all[18].id)
Answer.create(answer: ".unshift", correct: false, question_id: Question.all[18].id)
Answer.create(answer: ".sugar", correct: false, question_id: Question.all[19].id)
Answer.create(answer: ".spread", correct: false, question_id: Question.all[19].id)
Answer.create(answer: ".splice", correct: false, question_id: Question.all[19].id)
Answer.create(answer: ".slice", correct: true, question_id: Question.all[19].id)
puts "🌱 Seeding complete!"